import codecs
import re

refs = {
    "fan_soulmate": ('《爱在黎明破晓前》中试图用一天内完美的精神共鸣来抵抗生活琐碎漫长的杰西和赛琳娜；无数交友软件上机械滑动、死死坚信下一张面孔就能彻底终结自己所有孤独与残缺的现代人。', 'Jesse and Celine trying to use one day of perfect spiritual resonance to resist life\'s trivial length in Before Sunrise; modern people mechanically swiping on dating apps, firmly believing the next face will completely end all their loneliness and flaws.'),
    "fan_recognition": ('《爆裂鼓手》中哪怕双手打出血肉模糊、甚至在车祸后也爬上舞台只为换取导师弗莱彻哪怕一次肯定眼神的安德鲁；从小在极度贬低环境中长大、穷尽一生追求名利只为向当年嘲笑自己的人证明存在感的奋斗狂。', 'Andrew playing until his hands are bloody and crawling onto the stage after a car crash just for one approving glance from Fletcher in Whiplash; workaholics raised in extremely deprecating environments, exhausting their lives pursuing fame solely to prove their existence to those who mocked them.'),
    "fan_belonging": ('《搏击俱乐部》里通过失去自己的真实名字、沦为空壳般的“太空猴子”来在这个虚无社会中获取极端兄弟会归属感的迷茫青年；深信只有融入某种狂热的粉圈或邪教、自己的无价值人生才突然有了沉甸甸意义的极端粉丝。', 'Lost youths losing their real names to become hollow "Space Monkeys" to gain extreme brotherhood belonging in this nihilistic society in Fight Club; extreme fans convinced their worthless lives suddenly gain heavy meaning only by blending into a fanatical fandom or cult.'),
    "fan_savior_complex": ('《悲惨世界》中自己活在泥沼中却拼尽全力也要拯救妓女芳汀之女的冉阿让；现实关系中极度迷恋将边缘化堕落者拉出泥潭、通过这种施恩来确认自身强大和不可或缺的病态拯救者伴侣。', 'Jean Valjean living in the mire himself but exhausting all efforts to save the prostitute Fantine\'s daughter in Les Misérables; pathological savior partners deeply obsessed with pulling marginalized fallen people out of the mud, confirming their own power and indispensability through this grace.'),
    "fan_possession": ('《危情十日》中为了让自己最爱的作家永远留在身边并且只写自己喜欢的剧情、用铁锤毫不犹豫砸断对方双腿的安妮；那种会随时翻看伴侣手机所有记录、通过控制对方一切物理和虚拟行踪来获得安全感的极端控制狂。', 'Annie unhesitatingly breaking her favorite writer\'s legs with a sledgehammer to keep him forever by her side writing only plots she likes in Misery; extreme control freaks checking all their partner\'s phone records, gaining security by controlling all physical and virtual traces of the other.'),
    "fan_idol_mirror": ('《天才雷普利》里由于深深厌恶自己卑微庸俗的出身、最终残忍杀害富二代朋友并且彻底偷走其优雅人生身份的雷普利；整容成偶像的模样甚至完全模仿其言行举止、活生生抹杀掉自己原本‘丑陋’人格认同的极端私生饭。', 'Ripley, deeply disgusted by his humble origins, finally brutally murdering his rich friend and stealing his elegant life identity in The Talented Mr. Ripley; extreme sasaeng fans opting for plastic surgery to look like their idol and mimicking their every move, literally erasing their own original ‘ugly’ personality identity.'),
    "fan_unconditional_love": ('《被嫌弃的松子的一生》中无论被男人施加多少暴力与背叛、依然死咬着不放并且只要对方哪怕给出一丝残羹冷炙的爱意就能原谅一切的松子；在心理咨询室里因为无法面对成年人世界的有条件残酷法则、而退行到要求咨询师提供全能无条件抱持的边缘型障碍患者。', 'Matsuko, no matter how much violence and betrayal men inflict, clinging fiercely and forgiving everything if they give even a crumb of love in Memories of Matsuko; BPD patients in counseling rooms, unable to face the conditional cruel laws of the adult world, regressing to demand the counselor provide an omnipotent unconditional hold.'),
    "fan_symbiosis": ('《新世纪福音战士》中试图发动人类补完计划、打破所有绝对领域（A.T.力场）、将全人类化为毫无隔阂的原始LCL橙汁海洋的碇源堂；在虐恋关系中通过身体的极端疼痛与伤口、试图物理化地打破彼此皮囊隔离感受对方真实内核的重度受虐狂。', 'Gendo Ikari attempting to initiate the Human Instrumentality Project to break all Absolute Terror Fields and reduce all humanity to an unseparated primordial LCL orange juice ocean in Neon Genesis Evangelion; severe masochists in BDSM relationships trying to physically shatter their skin-bag isolation through extreme pain and wounds to feel the other\'s true core.'),
    "fan_being_needed": ('《隐秘的角落》中通过制造麻烦甚至命案然后再去解决、以此来让所有人发现“如果没了我你们根本活不下去”的极度自卑控制狂角色；在家庭中包办一切甚至阻碍孩子独立、只为永远享受“被绝对需要”这种权力春药的直升机父母。', 'Extremely inferior control freaks creating troubles or even murders then solving them to make everyone realize "you cannot live without me" as in The Bad Kids; helicopter parents in families handling everything and hindering children\'s independence just to forever enjoy the power-aphrodisiac of "being absolutely needed".'),
    "fan_hive_mind": ('《黑客帝国》里被接上无数管子、在营养液中像亿万颗毫无知觉的生物电池一样共同梦着矩阵虚幻安宁之梦的人类；面对复杂现代社会的撕裂与无力，狂热追求并主动将自我阉割以汇入某种狂热算法信息茧房或群体狂欢中的现代网民。', 'Humans hooked to countless tubes in nutrient fluid, dreaming a matrix illusion of peace together like billions of senseless bio-batteries in The Matrix; modern netizens facing the tears and powerlessness of complex society, frantically pursuing and actively auto-castrating themselves to merge into fanatical algorithmic echo chambers or mass carnivals.'),
    "fan_mentor": ('《星球大战》中因为极度渴望一个强大父亲形象的规训来平复内心恐惧、最终滑向黑暗面跪倒在帕尔帕廷皇帝脚下的安纳金；青年时期因为极度迷茫而将某个网红哲学博主或传销头子视作指路神明、哪怕对方逻辑漏洞百出也狂热护主的绝望信徒。', 'Anakin, deeply craving a strong father figure\'s discipline to calm his inner terror, eventually sliding to the dark side and kneeling to Emperor Palpatine in Star Wars; desperate believers in youth treating some influencer philosopher or MLM cult leader as a guiding deity, defending them fanatically despite glaring logical holes.'),
    "fan_loyalty": ('《忠犬八公》里数十年如一日在车站等待主人归来、哪怕跨越物种生死也将自我存在降维成一个“等待物”的八公所折射的人类投影；为了向邪教教主证明忠心、甚至不惜将自己刚出生的婴儿献祭出去以彻底摧毁自己人性的狂热信徒。', 'The human projection reflected by Hachiko waiting decades at the station for its owner to return, reducing its existence to a "waiting object" across species and death in Hachi; fanatic cultists willing to sacrifice their own newborn infants to totally destroy their humanity and prove loyalty to a cult leader.'),
    "fan_understanding": ('《她》（Her）中面对一台可以通过超强算力瞬间抓取他成千上万微小情绪、并给予无偏差精确反馈的AI系统而彻底沦陷的男主角西奥多；因为觉得“从来没人真正懂我”而拒绝现实社交、只对着不会反驳自己且全盘接受的定制虚拟模型倾诉最肮脏隐秘的死宅。', 'Theodore completely falling for an OS that can instantly capture his thousands of micro-emotions via super-computing and give precise, unbiased feedback in Her; hikikomoris rejecting real-life socialization feeling "no one ever truly understands me," venting their dirtiest secrets only to tailored virtual models that never argue and fully accept.'),
    "fan_home": ('《我是传奇》中在末日丧尸狂潮里把自己的房子焊死、设置重重结界试图在崩溃的宏大世界中保住针尖大“原本秩序”的罗伯特；在经历巨大社会心理创伤后，囤积几十年罐头食品将自己锁在地下室发誓再也不暴露在充满“毒素”的他人面前的末日生存狂。', 'Robert sealing his house tight against the zombie tide, setting layers of barriers trying to preserve a pinhead of "original order" in a collapsed grand world in I Am Legend; doomsday preppers hoarding decades of canned food and locking themselves in basements after colossal socio-psychological-trauma, swearing never to be exposed to others\' "toxins".'),
    "fan_twin_flame": ('《搏击俱乐部》中由于无法忍受自己懦弱空虚的白领生活，而在精神世界硬生生捏造出一个充满野性、暴力且能够与自己完美对打交锋的“双生子”泰勒；那种在每段恋爱中都在试图把对方强行改造成世界上的另一个自己、稍有偏差便暴怒认为“你根本不是我的双子火焰”的自恋狂。', 'The protagonist unable to endure his cowardly empty white-collar life, forcefully fabricating in his mind a wild, violent "twin" Tyler who perfectly boxes and clashes with him in Fight Club; narcissists trying to forcibly transform partners into another version of themselves in every romance, erupting in rage at any deviation believing "you are absolutely not my twin flame".'),
    "fan_confession": ('《七宗罪》里其实早已给自己定下了骄傲之罪、只能通过最终挑衅受害者对自己扣下扳机来完成一场华丽流血大告解的连环杀手约翰·杜；每天在匿名树洞长篇大论忏悔自己如何背叛婚姻、虽然渴望被辱骂却毫无改过之心、纯粹是在享受“被当众凌迟的快感”的道德暴露狂。', 'Serial killer John Doe who had long convicted himself of Envy, completing a grand bloody confession only by provoking the victim to pull the trigger on him in Se7en; moral exhibitionists typing long anonymous confessions daily about betraying their marriages, craving insults with no intention of repenting, purely enjoying the "thrill of public execution".'),
    "fan_legacy": ('《星际穿越》中为了让人类种族的DNA序列能播撒到外太空繁衍下去，不惜牺牲现在这批活人个体的布兰德教授的终极图谋；临终前固执地逼迫同性恋儿子必须去借腹代孕生个有血缘的孙子，以此来抵抗自己基因在这个宇宙中永远熄灭的濒死老人。', 'Professor Brand\'s ultimate scheme to sacrifice the current generation of living individuals just to seed humanity\'s DNA sequence for outer space multiplication in Interstellar; dying elders stubbornly forcing gay sons to enact surrogacy just to have blood-related grandchildren to resist their genes forever extinguishing in the cosmos.'),
    "fan_communication": ('《降临》里不惜承受提前预知亲生女儿未来惨死的一生绝望，也要强行去学会那完全非线性的“七肢桶”外星语言、只为穿透物种深渊的语言学家露易丝；因为极度渴望打破与狗之间的障碍、花了几十年时间用各种荒唐脑电波仪器连接动物妄图实现思维直连的怪人。', 'Linguist Louise enduring the lifelong despair of foreseeing her daughter\'s tragic death just to learn the completely non-linear Heptapod alien language to pierce the species abyss in Arrival; eccentrics spending decades strapping absurd EEG machines to dogs, craving to break the barrier through direct brainwave links.'),
    "fan_pact": ('《浮士德》中深切感知到人类知识与生命的双重可悲尽头后，签下哪怕出卖不朽灵魂也要立刻换取现世无尽体验与魔力的血之契约的浮士德博士；在婚姻或结拜中试图用斩鸡头、喝血酒甚至在对方身上纹下这辈子都洗不掉的带有剧痛的誓言名字、来掩盖对被抛弃恐慌的极端不安全感患者。', 'Doctor Faust, deeply sensing the pathetic dual ends of human knowledge and life, signing a blood pact to immediately trade his immortal soul for boundless worldly experience and magic in Faust; extreme insecurity sufferers in marriage or sworn-brotherhood trying to mask abandonment panic via chopping chicken heads, drinking blood wine, or tattooing agonizing unerasable pledge names on each other.'),
    "fan_shared_secret": ('《绳索》中两个自诩为超人的精英高材生为了证明自己凌驾于凡俗道德之上，合谋勒死了一个无辜同学将其藏在随时举办晚宴的客厅箱子里、以此彻底绑死两人关系的极端同性罪犯；在职场上通过共同参与一场绝对会坐牢的财务造假案、在互相交出致命把柄的战栗感中获得不可思议之性高潮般忠诚的利益共同体。', 'Two self-proclaimed elite supermen conspiring to strangle an innocent classmate and hiding him in a chest during a living-room party, proving they transcend vulgar morals while hopelessly binding their relationship in Rope; corporate cohorts participating in absolutely jailable financial fraud together, attaining unbelievable orgasmic loyalty through the thrill of handing over fatal blackmail.'),
    "fan_guardianship": ('《这个杀手不太冷》中通过用生命保护玛蒂尔达这个纯洁孤儿，从而在内心深渊为自己双手沾满鲜血的烂泥人生找到最后一块救赎飞地的杀手莱昂；那些以“外界全都是想害你的坏人”为由将自己有缺陷的孩子完全软禁隔离起来，通过这种绝对保护权来扮演上帝的窒息看护者。', 'Hitman Leon finding his final salvation enclave for his blood-soaked, muddy life in the inner abyss by guarding the pure orphan Mathilda with his life in Leon: The Professional; suffocating caretakers putting their disabled children under total house arrest citing "the outside is full of bad people trying to hurt you," playing God via this absolute protection power.'),
    "fan_becoming_other": ('《移魂都市》或者《逃出绝命镇》里那些本已衰老枯竭却偏执地想要夺走年轻人强健肉体，甚至直接将其意识挤出躯壳取而代之的剥夺者；在互联网狂热偷窃某个死者或名人的所有照片跟细节记录、天长日久后自己都在精神分裂中深信本尊就是自己的深度雷普利症候群患者。', 'The snatchers who, already aged and decaying, paranoidly want to steal young robust bodies, even directly squeezing out their consciousness to supplant them as seen in Get Out; deep Ripley Syndrome patients frantically stealing all photos and detailed records of a dead person or celebrity online, developing schizophrenia over time to deeply believe the persona is their true self.'),
    "fan_absolute_trust": ('《无间道》中处在随时可能暴露并横死的卧底地狱边缘，将唯一掌握自己真实身份密码的长官视为什么都可以托付的绝对定海神针绝望情绪；在黑帮或极端雇佣兵团队中，要求对方在背对枪口的情况下依然连一厘米肌肉都不抖动、去测试那种违背人类所有求生本能的病态服从游戏。', 'The desperate emotion of standing on the hellish edge of sudden deadly exposure, treating the sole commanding officer who holds the real identity code as an absolute anchor capable of bearing anything in Infernal Affairs; gangs or extreme mercs making others face away from gunpoints without twitching an inch of muscle, testing sick obedience games that defy all human survival instincts.'),
    "fan_reconciliation": ('《星球大战：绝地归来》中不论达斯·维达曾经斩断过自己的手且屠杀百万生灵，卢克也要放下光剑在对方因良心未泯而死去的最后半秒彻底原谅这位残暴父亲的终极幻想；在现实狗血家庭剧中被虐待了几十年抛弃的女儿、却在对方癌症晚期病床前瞬间消除所有滔天恨意痛哭流涕的虚假人工降糖大团圆。', 'The ultimate fantasy of Luke lowering his lightsaber to totally forgive Darth Vader in his dying half-second of conscience, disregarding his hand-chopping and slaughtering of millions in Star Wars: Return of the Jedi; the fake artificially-sweetened grand finale in real-life melodramatic soap operas where a daughter abused and abandoned for decades instantly erases all towering hatred to weep at the terminal cancer bedside.')
}

def_ens = {
    "fan_legacy": "Craving to continue life through descendants, apprentices, or works.",
    "fan_communication": "Trying to cross an insurmountable species or dimensional gap to understand and merge with completely unnamable existences.",
    "fan_pact": "Signing an unbreakable, absolute life-or-death pact with a person or god.",
    "fan_shared_secret": "Forcibly binding the fates of both parties by jointly committing or keeping an unforgivable sin.",
    "fan_guardianship": "Establishing one's god's-eye view by absolutely monopolizing the right to protect a weak existence (child/apprentice/hope).",
    "fan_becoming_other": "Completely abandoning one's physical and psychological boundaries, extremely substituting or physically occupying another person's life experience.",
    "fan_absolute_trust": "Trying to place interpersonal relationships in an absolute vacuum environment, looking for an object that 100% wouldn't betray themselves even facing a gunpoint.",
    "fan_reconciliation": "Reaching an absolute, unreserved understanding and embrace with the nemesis, shadow, or abuser who brought the deepest pain in life."
}

path = "data/engine_core/m3/group_c.ts"
with codecs.open(path, "r", "utf-8") as f:
    content = f.read()

# First add def_ens where missing
for key, def_en in def_ens.items():
    def_en = def_en.replace('"', '\\"')
    pattern = r'(id:\s*"' + key + r'".*?def:\s*".*?",)(\s*core:)'
    replacement = r'\1\n        defEn: "' + def_en + '",\2'
    content = re.sub(pattern, replacement, content, flags=re.DOTALL)

# Then add refs globally
for key, (zh, en) in refs.items():
    zh = zh.replace('"', '\\"')
    en = en.replace('"', '\\"')
    pattern = r'(id:\s*"' + key + r'".*?coreEn:.*?)(,?\s*\n\s*})'
    replacement = r'\1,\n        reference: "' + zh + '",\n        referenceEn: "' + en + '"\2'
    content = re.sub(pattern, replacement, content, flags=re.DOTALL)

with codecs.open(path, "w", "utf-8") as f:
    f.write(content)
