import codecs
import re

data = {
    "fan_throne": ('《教父》中为了保护家族而最终踏上王座、却彻底变成孤家寡人的麦克·柯里昂；现实中为了权力不惜牺牲一切亲属关系的独裁者。', "Michael Corleone stepping onto the throne to protect his family but ultimately becoming utterly isolated in The Godfather; real-life dictators sacrificing all family ties for power."),
    "fan_masterpiece": ('《莫扎特传》中耗尽生命也要完成《安魂曲》、试图以此超越凡人必死宿命的莫扎特；为了雕刻出完美的圣母像而将自己关在工坊内直至活生生饿死的中世纪艺术家。', 'Mozart exhausting his life to complete the Requiem, trying to transcend mortal fate in Amadeus; medieval artists locking themselves in workshops until starved to death just to sculpt the perfect Madonna.'),
    "fan_truth": ('《黑客帝国》中宁愿接受残酷凄凉的真实废墟、也坚决吞下红色药丸拒绝虚假安逸的尼奥；为了探求宇宙终极物理公式而陷入严重精神分裂症、无法正常生活的天才数学家。', 'Neo resolutely swallowing the red pill to face the cruel, desolate ruins of reality over comfortable illusion in The Matrix; genius mathematicians falling into severe schizophrenia, unable to live normally in pursuit of the ultimate physics formula.'),
    "fan_ascension": ('《2001太空漫游》中抛弃肉身、进化为在宇宙中自由穿梭星童的鲍曼；硅谷狂热的超人类主义者，试图将意识上传云端以摆脱“糟糕的碳基躯壳”。', 'Bowman discarding his flesh to evolve into a Star Child freely drifting through the universe in 2001: A Space Odyssey; fanatic transhumanists in Silicon Valley trying to upload consciousness to the cloud to escape the \'terrible carbon-based shell\'.'),
    "fan_revision": ('《终结者》中一次次穿越回现代，试图杀掉或者拯救那个关键点领袖以改写人类被机器抹杀的命运的战士；对特定历史遗憾耿耿于怀，在脑内进行千万次兵棋推演妄图“如果当初那样做”的创伤幸存者。', 'Warriors repeatedly traveling back to modern times to kill or save the crucial leader and rewrite humanity\'s doom by machines in The Terminator; trauma survivors brooding over historical regrets, running millions of mental war games of \'if only I did that\'.'),
    "fan_jackpot": ('《指环王》里令人不择手段、带来无限权力的至尊魔戒；现实中为了虚空加密货币暴富神话而抵押所有房产甚至家破人亡的疯狂赌徒。', 'The One Ring driving men to any means and promising limitless power in The Lord of the Rings; crazed gamblers in reality mortgaging all properties and ruining their families for the myth of empty cryptocurrency wealth.'),
    "fan_omniscience": ('《沙丘》中吞下生命之水后获得历代先祖记忆与预见未来能力、却被全知神格剥夺了常人情感的保罗；现代因为患上严重的信息错失恐惧症（FOMO）而必须24小时监控多个屏幕上滚动的庞大数据的狂魔。', 'Paul gaining ancestors\' memories and future-sight after drinking the Water of Life, but having his human emotions stripped by omniscient godhood in Dune; modern maniacs monitoring rolling massive data across multiple screens 24/7 due to severe FOMO.'),
    "fan_immortality": ('《木星上行》中为了提取寿命而不惜收割整个地球人口将其制成青春血清的宇宙贵族；历史上痴迷于炼丹长生、吞食致命重金属试图达到肉身不朽的封建帝王。', 'Cosmic nobles harvesting entire Earth populations to process them into youth serum to extract lifespan in Jupiter Ascending; historical feudal emperors obsessed with alchemy, consuming lethal heavy metals seeking bodily immortality.'),
    "fan_creator": ('《西部世界》里为了创造出具有真正“意识”的完美仿生人而引发一场物种级别血腥反叛的福特博士；深信自己可以通过培养皿中的干细胞拼凑出一个完全按照自己蓝图行事的全智婴儿的疯狂科学家。', 'Dr. Ford sparking a species-level bloody rebellion to create perfect hosts with true \'consciousness\' in Westworld; mad scientists deeply believing they can piece together an omniscient infant from petri dish stem cells to act exactly per their blueprint.'),
    "fan_total_control": ('《楚门的世界》中将一个人从出生到恋爱所有细节都控制在巨大摄影棚剧本之下的导演克里斯托弗；在亲密关系中要求伴侣随时开启位置共享、精确到分钟汇报行程的控制狂。', 'Christof, the director controlling every detail of a man\'s life from birth to romance within a giant studio script in The Truman Show; control freaks in relationships demanding partners turn on location sharing 24/7 and report itineraries down to the minute.'),
    "fan_invulnerability": ('《一拳超人》中因为过于强大而失去战斗激情和一切常人恐惧、陷入深深存在主义虚无的琦玉老师；战场上因为穿着重型防弹装甲而感到安全，一旦脱下便觉得浑身赤裸即将碎裂的PTSD士兵。', 'Saitama experiencing deep existential nihilism, losing battle passion and ordinary fear because of being overwhelmingly strong in One Punch Man; PTSD soldiers on battlefields feeling safe only in heavy bulletproof armor, feeling naked and shattering the moment it is removed.'),
    "fan_mind_reading": ('《偷听女人心》里突然能听到所有女性心声、借此操控人心却最终不堪重负的男主角；临床偏执狂患者深信别人一个微小的皱眉都是在内心对自己进行恶毒咒骂与算计。', 'The protagonist suddenly able to hear all women\'s thoughts, using it to manipulate minds but eventually overwhelmed in What Women Want; clinical paranoids convinced that another\'s slight frown is a vicious internal curse and calculation against them.'),
    "fan_invisibility": ('《透明人》里因为获得了隐形能力、社会道德束缚瞬间坍塌而迅速堕落为强奸犯和杀人魔的科学家；在网络匿名论坛里披着无名氏马甲，毫无顾忌地宣泄最阴暗暴力欲望的键盘侠。', 'The scientist rapidly degenerating into a rapist and murderer as social moral constraints instantly collapse upon gaining invisibility in Hollow Man; keyboard warriors hiding behind Anonymous avatars on internet forums, recklessly venting their darkest violent desires.'),
    "fan_prophecy": ('《少数派报告》中依靠三个先知提前看到谋杀案画面并进行预先逮捕、却被“决定论”死局反噬的治安系统；为了逃避不确定性焦虑而把一切人生重大决策（结婚/投资）完全交给塔罗牌和星象占卜的迷信者。', 'The PreCrime system relying on three Precogs to see murder visions and make pre-arrests, only to be bitten back by the deterministic dead-end in Minority Report; superstitious people entirely handing over major life decisions (marriage/investments) to Tarot and astrology to escape uncertainty anxiety.'),
    "fan_world_domination": ('《复仇者联盟》中坚信宇宙资源有限，为了达成残酷平衡而随机弹指抹杀宇宙一半生命的灭霸；在战略游戏中试图将整个地球版图全部涂成同一种颜色、绝不允许任何多元文化共存的强迫症玩家。', 'Thanos firmly believing cosmic resources are limited, snapping away half of all life to achieve cruel balance in The Avengers; OCD gamers trying to paint the entire Earth map a single color in strategy games, absolutely forbidding any multicultural coexistence.'),
    "fan_icon": ('《黑袍纠察队》中表面光鲜亮丽、被万众疯狂崇拜，背地里却需要靠残杀无辜和母乳来填补巨大虚空内心的祖国人；为了在社交媒体上维持网红人设、不惜负债买奢侈品并伪造完美生活最终抑郁的现代青年。', 'Homelander, glamorous and frantically worshipped on the surface, but needing to slaughter innocents and drink breast milk to fill the giant void inside in The Boys; modern youths going into debt buying luxury goods and faking perfect lives to maintain social media influencer personas, eventually suffering depression.'),
    "fan_monopoly": ('《华尔街之狼》中为了吞得所有利润而彻底异化为野兽、疯狂操纵股票吞噬别人骨血的乔丹·贝尔福特；在某个电商或行业领域为了消灭最后一个竞争对手而甚至动用底线手段的巨头企业。', 'Jordan Belfort thoroughly alienating into a beast, crazily manipulating stocks and devouring others\' bones and blood to swallow all profits in The Wolf of Wall Street; corporate giants using bottom-line tactics just to eliminate the very last competitor in an e-commerce or industry sector.'),
    "fan_lawgiver": ('《死亡笔记》中捡到死神笔记本后，便自诩为“新世界的神”、按照自己的绝对正邪标准开始跨国杀戮罪犯的夜神月；现实中私设刑堂、认为现行法律过于软弱而自己动手处决人贩子的私刑执行者。', 'Light Yagami calling himself \'God of the new world\' upon picking up the Death Note, beginning cross-border slaughter of criminals according to his absolute standard of justice in Death Note; real-life vigilantes setting up private tortures, thinking current laws are too weak and executing human traffickers themselves.'),
    "fan_judgement": ('《守望者》中为了预防美苏核战，不惜制造出一场虚假的曼哈顿博士暴走将数百万无辜市民瞬间汽化以此逼迫人类团结的法老王；深信末日审判即将来临、决定自己动手净化那些“异端分子”的极端邪教首脑。', 'Ozymandias vaporizing millions of innocent civilians through a fake Dr. Manhattan rampage to force human unity and prevent US-Soviet nuclear war in Watchmen; extreme cult leaders deeply believing the Last Judgment is coming and deciding to clean the \'heretics\' themselves.'),
    "fan_digital_upload": ('《超验骇客》里身体死后被妻子将意识上传至超级电脑，最终变成一个吞噬全球网络、妄图同化所有物理世界的无处不在之神的威尔博士；现实中签署协议、希望在死后将大脑切片扫描以求在未来模拟器里复活的狂热程序员。', 'Dr. Will, uploaded to a supercomputer by his wife after physical death, becoming an omnipresent god devouring the global network and trying to assimilate all physical worlds in Transcendence; fanatic programmers signing agreements hoping to slice and scan their brains after death for future revival in a simulator.'),
    "fan_velocity": ('《闪电侠》中因为跑得太快而直接撕裂时空屏障、引发了“闪点”从而彻底摧毁又重构了整个宇宙因果律的巴里；追求极端多巴胺推背感、在深夜的高速公路上闭着眼睛以时速三百公里狂飙体验频死快感的地下赛车狂。', 'Barry running so fast he tears the space-time barrier, triggering Flashpoint to utterly destroy and reconstruct universally causality in The Flash; underground racers pursuing extreme dopamine pushes, tearing down late-night highways at 300 km/h with eyes closed to experience near-death highs.'),
    "fan_superintelligence": ('《超体》中大脑被药物开发到100%、最终肉体彻底消散化为一枚黑色U盘、将全宇宙知识解析为0与1的露西；为了优化睡眠与工作效率，将生活一切微小变量（饮食/心率）都精准记录且陷入强制算法化崩溃的量化自我（Quantified Self）走火入魔者。', 'Lucy whose brain was drugged to 100% capacity, ultimately dissolving her flesh into a black USB flash drive, parsing all cosmic knowledge into 0s and 1s in Lucy; \'Quantified Self\' obsessives charting every micro-variable (diet/heart rate) to optimize sleep/work, crashing into enforced algorithmic breakdowns.'),
    "fan_godslayer": ('《战神》中被诸神算计杀害妻女后，满身涂满骨灰、一路屠杀整个奥林匹斯神系以平息内心狂怒的奎托斯；对于任何权威结构（老板/政府/父亲）都本能性产生暴烈杀意与对抗动作的极致无政府主义破坏者。', 'Kratos, tricked by gods into killing his wife and daughter, covered in their ashes and slaughtering the entire Olympian pantheon to appease his fury in God of War; extreme anarchist destroyers instinctively generating violent murderous intent and confrontational actions toward any authority structure (boss/government/father).'),
    "fan_empire_building": ('《基地》中预见到银河帝国毁灭、为此建立一套跨越数千年数学心理史学蓝图来操控万兆人口重建新帝国的哈里·谢顿；某些巨型资本创始人试图用算法物流和打卡系统将数十万人类员工强行格式化为完美执行指令齿轮的反乌托邦梦幻。', 'Hari Seldon foreseeing the Galactic Empire\'s ruin, setting up a millennia-spanning psychohistory scheme manipulating trillions to rebuild a new empire in Foundation; mega-capital founders trying to forcibly format hundreds of thousands of human employees into perfectly executing cogs via algorithmic logistics and punch-in systems in a dystopian dream.')
}

path = "data/engine_core/m3/group_b.ts"
with codecs.open(path, "r", "utf-8") as f:
    content = f.read()

for key, (zh, en) in data.items():
    zh = zh.replace('"', '\\"')
    en = en.replace('"', '\\"')
    pattern = r'(id:\s*"' + key + r'".*?coreEn:.*?)(,?\s*\n\s*})'
    replacement = r'\1,\n        reference: "' + zh + '",\n        referenceEn: "' + en + '"\2'
    content = re.sub(pattern, replacement, content, flags=re.DOTALL)

with codecs.open(path, "w", "utf-8") as f:
    f.write(content)
