import os
import re

def process_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    
    for core_en_target, ref_cn, ref_en in replacements:
        replacement = f'{core_en_target}\n      reference: "{ref_cn}",\n      referenceEn: "{ref_en}",'
        content = content.replace(core_en_target, replacement)
        
    with open(filepath, 'w') as f:
        f.write(content)

reps_c = [
    ('coreEn: "Civ wreckage vs savagery. Faith as patch. | Anchor ($): M1 Regression_Hole",',
     '《第七封印》(1957, 英格玛·伯格曼) / 《玫瑰之名》(1986, 让-雅克·阿诺)',
     '\\"The Seventh Seal\\" (1957, Ingmar Bergman) / \\"The Name of the Rose\\" (1986, Jean-Jacques Annaud)'),
    ('coreEn: "Honor econ. Death is not the end. | Anchor ($): M5 Death_Sunflower",',
     '《维京传奇》(2013-2020, 剧集) / 《北欧人》(2022, 罗伯特·艾格斯)',
     '\\"Vikings\\" (2013-2020, Series) / \\"The Northman\\" (2022, Robert Eggers)'),
    ('coreEn: "Holy oaths vs bloody reality. Absolute altruism causes absolute cruelty. | Anchor ($): M6 Holy_Delirium",',
     '《天国王朝》(2005, 雷德利·斯科特) / 《十字军圣战》(2001, 纪录片)',
     '\\"Kingdom of Heaven\\" (2005, Ridley Scott) / \\"The Crusades\\" (2001, BBC)'),
    ('coreEn: "Theology of light. Smallness in abyssal stone spaces. | Anchor ($): M4 Gaze_Deprivation",',
     '《巴黎圣母院》(1956, 让·德拉努瓦) / 《圣女贞德蒙难记》(1928, 卡尔·西奥多·德莱叶)',
     '\\"The Hunchback of Notre Dame\\" (1956, Jean Delannoy) / \\"The Passion of Joan of Arc\\" (1928, Carl Theodor Dreyer)'),
    ('coreEn: "Death equality. Collective collapse of taboo. | Anchor ($): M2 Plague_Flaying",',
     '《黑死病》(2010, 克里斯托弗·史密斯) / 《十日谈》(1971, 皮埃尔·保罗·帕索里尼)',
     '\\"Black Death\\" (2010, Christopher Smith) / \\"The Decameron\\" (1971, Pier Paolo Pasolini)'),
    ('coreEn: "Nihilism behind boom. Extreme loneliness at power peak. | Anchor ($): M3 Poetic_Psychedelia",',
     '《妖猫传》(2017, 陈凯歌) / 《刺客聂隐娘》(2015, 侯孝贤)',
     '\\"Legend of the Demon Cat\\" (2017, Chen Kaige) / \\"The Assassin\\" (2015, Hou Hsiao-Hsien)'),
    ('coreEn: "Soft bones. Minimalist rituals fighting Northern savages. | Anchor ($): M4 Format_Zen",',
     '《清明上河图密码》(概念) / 《大明劫》(2013, 王竞)',
     '\\"Along the River During the Qingming Festival\\" (Concept) / \\"Fall of Ming\\" (2013, Wang Jing)'),
    ('coreEn: "Dimension drop. Powerlessness in grand history grinder. | Anchor ($): M5 Wild_Stripping",',
     '《蒙古王》(2007, 谢尔盖·波德罗夫) / 《马可·波罗》(2014-2016, 剧集)',
     '\\"Mongol\\" (2007, Sergei Bodrov) / \\"Marco Polo\\" (2014-2016, Series)'),
    ('coreEn: "Beauty vs filth. Extreme formalism suppressing subconscious demons. | Anchor ($): M3 Grudge_Phantom",',
     '《阴阳师》(2001, 泷田洋二郎) / 《辉夜姬物语》(2013, 高畑勋)',
     '\\"Onmyoji\\" (2001, Yōjirō Takita) / \\"The Tale of the Princess Kaguya\\" (2013, Isao Takahata)'),
    ('coreEn: "Cheap loyalty. Seeking a lord amid endless betrayals. | Anchor ($): M1 Seppuku_Reset",',
     '《乱》(1985, 黑泽明) / 《影武者》(1980, 黑泽明)',
     '\\"Ran\\" (1985, Akira Kurosawa) / \\"Kagemusha\\" (1980, Akira Kurosawa)'),
    ('coreEn: "Tyranny of truth. Man-made hell of fear. | Anchor ($): M4 Symbolic_Mysophobia",',
     '《戈雅之灵》(2006, 米洛斯·福尔曼) / 《圣女贞德》(1999, 吕克·贝松)',
     '\\"Goya\'s Ghosts\\" (2006, Miloš Forman) / \\"The Messenger: The Story of Joan of Arc\\" (1999, Luc Besson)'),
    ('coreEn: "Holy-money intercourse and tear. | Anchor ($): M1 Golden_Grail",',
     '《骑士陨落》(2017-2019, 剧集) / 《达·芬奇密码》(2006, 朗·霍华德)',
     '\\"Knightfall\\" (2017-2019, Series) / \\"The Da Vinci Code\\" (2006, Ron Howard)'),
    ('coreEn: "Premature reason. Science sparks surrounded by religion. | Anchor ($): M3 Wisdom_Flashpoint",',
     '《神医》(2013, 菲利普·斯托茨) / 《一千零一夜》(2015, 米格尔·戈麦斯)',
     '\\"The Physician\\" (2013, Philipp Stölzl) / \\"Arabian Nights\\" (2015, Miguel Gomes)'),
    ('coreEn: "Immortal phantasm. Nation drained for stone universe. | Anchor ($): M4 Petrified_Rhapsody",',
     '《花样年华》(2000, 王家卫 - 结尾概念) / 《古墓丽影》(2001, 西蒙·韦斯特)',
     '\\"In the Mood for Love\\" (2000, Wong Kar-wai - ending) / \\"Lara Croft: Tomb Raider\\" (2001, Simon West)'),
    ('coreEn: "Power vacuum game. Endless anxiety of micro-states. | Anchor ($): M3 Patchwork_Puzzle",',
     '《铁血神探》(2001, 皮托夫) / 《白王后》(2013, 剧集)',
     '\\"Vidocq\\" (2001, Pitof) / \\"The White Queen\\" (2013, Series)'),
    ('coreEn: "Holy madness. Ordinary subject sacrificed by Other. | Anchor ($): M2 Oracle_Flesh",',
     '《圣女贞德》(1999, 吕克·贝松) / 《秋之白华》(2011, 霍建起)',
     '\\"The Messenger: The Story of Joan of Arc\\" (1999, Luc Besson) / \\"The Seal of Love\\" (2011, Huo Jianqi)'),
    ('coreEn: "Contract cruelty. Money dissolves blood/faith. | Anchor ($): M1 Contract_Vampirism",',
     '《威尼斯商人》(2004, 迈克尔·雷德福) / 《美第奇家族》(2016-2019, 剧集)',
     '\\"The Merchant of Venice\\" (2004, Michael Radford) / \\"Medici\\" (2016-2019, Series)'),
    ('coreEn: "Dimension drop. Autistic logic meets alien sys. | Anchor ($): M4 System_Incompatible",',
     '《启示》(2006, 梅尔·吉布森) / 《新世界》(2005, 泰伦斯·马力克)',
     '\\"Apocalypto\\" (2006, Mel Gibson) / \\"The New World\\" (2005, Terrence Malick)'),
    ('coreEn: "Violent mercy. Kill to protect void base. | Anchor ($): M6 Killing_Salvation",',
     '《七武士》(1954, 黑泽明) / 《拔剑》(1962, 三隅研次)',
     '\\"Seven Samurai\\" (1954, Akira Kurosawa) / \\"Kiru\\" (1962, Kenji Misumi)'),
    ('coreEn: "Civ handover. New engine rolls over medieval walls. | Anchor ($): M4 Format_Crush",',
     '《德古拉元年》(2014, 加里·肖尔) / 《帝国崛起：奥斯曼》(2020, 剧集)',
     '\\"Dracula Untold\\" (2014, Gary Shore) / \\"Rise of Empires: Ottoman\\" (2020, Series)')
]

process_file('/Users/lujiaqi/Desktop/【迷雾学派】爱欲视觉拓扑学 2-24版/data/engine_surface/SUR2/group_c.ts', reps_c)

reps_d = [
    ('coreEn: "Cost of beauty. Dirty plots birthed holy art. | Anchor ($): M3 Poison_Bloom",',
     '《波吉亚家族》(2011-2013, 剧集) / 《翡冷翠名姬》(1998, 马歇尔·赫斯科维兹)',
     '\\"The Borgias\\" (2011-2013, Series) / \\"Dangerous Beauty\\" (1998, Marshall Herskovitz)'),
    ('coreEn: "Pains of reason. Mind boom vs old sys kickback. | Anchor ($): M1 Etched_Ghost",',
     '《安德烈·卢布廖夫》(1966, 安德烈·塔可夫斯基) / 《玛戈王后》(1994, 帕特里斯·谢罗)',
     '\\"Andrei Rublev\\" (1966, Andrei Tarkovsky) / \\"Queen Margot\\" (1994, Patrice Chéreau)'),
    ('coreEn: "Geopolitic bloat. Human ego breaks borders, old gods die. | Anchor ($): M6 Horizon_Overload",',
     '《1492：征服天堂》(1992, 雷德利·斯科特) / 《加勒比海盗》(2003, 戈尔·维宾斯基)',
     '\\"1492: Conquest of Paradise\\" (1992, Ridley Scott) / \\"Pirates of the Caribbean\\" (2003, Gore Verbinski)'),
    ('coreEn: "Brief freedom dream. Doomed utopia rejecting Other. | Anchor ($): M5 Reverse_Blackflow",',
     '《黑帆》(2014-2017, 剧集) / 《怒海争锋》(2003, 彼得·威尔)',
     '\\"Black Sails\\" (2014-2017, Series) / \\"Master and Commander\\" (2003, Peter Weir)'),
    ('coreEn: "Stiff court vs active rivers-lakes. Desire twisted by Ancestral Law. | Anchor ($): M4 Seal_Suppression",',
     '《绣春刀》(2014, 路阳) / 《大明王朝1566》(2007, 剧集)',
     '\\"Brotherhood of Blades\\" (2014, Lu Yang) / \\"Ming Dynasty in 1566\\" (2007, Series)'),
    ('coreEn: "Frozen classes. Seeking instant ticks in floating world. | Anchor ($): M3 Ukiyo_Hollow",',
     '《恶女花魁》(2007, 蜷川实花) / 《静静的决斗》(1949, 黑泽明)',
     '\\"Sakuran\\" (2007, Mika Ninagawa) / \\"The Quiet Duel\\" (1949, Akira Kurosawa)'),
    ('coreEn: "Spectacle rule. Ultimate visual lavish disarming subjects. | Anchor ($): M4 Dazzling_Auth",',
     '《凡尔赛》(2015-2018, 剧集) / 《王者之舞》(2000, 热拉尔·科尔比奥)',
     '\\"Versailles\\" (2015-2018, Series) / \\"Le Roi Danse\\" (2000, Gérard Corbiau)'),
    ('coreEn: "Tyranny of ideals. Rational society remake births cruelty. | Anchor ($): M1 Rational_Beheading",',
     '《丹东》(1983, 安杰伊·瓦伊达) / 《悲惨世界》(2012, 汤姆·霍珀)',
     '\\"Danton\\" (1983, Andrzej Wajda) / \\"Les Misérables\\" (2012, Tom Hooper)'),
    ('coreEn: "Lust is politic. King\'s desire forces law remake. | Anchor ($): M2 Power_Desire_Mirror",',
     '《都铎王朝》(2007-2010, 剧集) / 《另一个波琳家的女孩》(2008, 贾斯汀·查德维克)',
     '\\"The Tudors\\" (2007-2010, Series) / \\"The Other Boleyn Girl\\" (2008, Justin Chadwick)'),
    ('coreEn: "Longing for immortal. Draining treasury for tomb. | Anchor ($): M6 Undead_Canopy",',
     '《阿克巴大帝》(2008, 阿舒托史·哥瓦力克) / 《泰姬陵》(纪录片)',
     '\\"Jodhaa Akbar\\" (2008, Ashutosh Gowariker) / \\"Taj Mahal\\" (Documentary)'),
    ('coreEn: "Power shift. Introvert explosion under spy web. | Anchor ($): M3 Rose_Thorn_Web",',
     '《伊丽莎白：黄金时代》(2007, 谢加·凯普尔) / 《莎翁情史》(1998, 约翰·麦登)',
     '\\"Elizabeth: The Golden Age\\" (2007, Shekhar Kapur) / \\"Shakespeare in Love\\" (1998, John Madden)'),
    ('coreEn: "Wealth\'s curse. Imperial weakness from silver influx. | Anchor ($): M1 Silver_Stagflation",',
     '《佣兵传奇》(2006, 阿古斯丁·迪亚斯·亚内斯) / 《无敌舰队》(2015, 纪录片)',
     '\\"Alatriste\\" (2006, Agustín Díaz Yanes) / \\"Armada: 12 Days to Save England\\" (2015, BBC)'),
    ('coreEn: "Moral pathology. Hunting neighbors via guilt projection. | Anchor ($): M4 Hysteric_Projection",',
     '《女巫》(2015, 罗伯特·艾格斯) / 《塞勒姆》(2014-2017, 剧集)',
     '\\"The Witch\\" (2015, Robert Eggers) / \\"Salem\\" (2014-2017, Series)'),
    ('coreEn: "Honor devalued. Samurai-to-bureaucrat structural mismatch. | Anchor ($): M3 Status_Deadlock",',
     '《黄昏的清兵卫》(2002, 山田洋次) / 《切腹》(1962, 小林正树)',
     '\\"The Twilight Samurai\\" (2002, Yoji Yamada) / \\"Harakiri\\" (1962, Masaki Kobayashi)'),
    ('coreEn: "Capital\'s raw wildness. No history, just swap frontier. | Anchor ($): M1 Rootless_Code",',
     '《纽约黑帮》(2002, 马丁·斯科塞斯) / 《拓荒者》(2020, 剧集)',
     '\\"Gangs of New York\\" (2002, Martin Scorsese) / \\"Barkskins\\" (2020, Series)'),
    ('coreEn: "Wild frontier freedom. Power deterritorialization in super-power crevices. | Anchor ($): M5 Nomadic_Deterritorialization",',
     '《火与剑》(1999, 耶日·霍夫曼) / 《静静的顿河》(1957, 谢尔盖·格拉西莫夫)',
     '\\"With Fire and Sword\\" (1999, Jerzy Hoffman) / \\"And Quiet Flows the Don\\" (1957, Sergei Gerasimov)'),
    ('coreEn: "Paradigm leap. Divinity exits, soul disenchants to cold math. | Anchor ($): M4 Equation_Dissolution",',
     '《达·芬奇的恶魔》(2013-2015, 剧集) / 《万物理论》(2014, 詹姆斯·马什)',
     '\\"Da Vinci\'s Demons\\" (2013-2015, Series) / \\"The Theory of Everything\\" (2014, James Marsh)'),
    ('coreEn: "Money monetizes Other. Thrilling leap from theocracy to capital. | Anchor ($): M1 Debt_Salvation",',
     '《美第奇家族：翡冷翠名门》(2016, 剧集) / 《达芬奇的恶魔》(2013, 剧集)',
     '\\"Medici: Masters of Florence\\" (2016, Series) / \\"Da Vinci\'s Demons\\" (2013, Series)'),
    ('coreEn: "Soul colonization. Local worship subtly survives in Catholic shell. | Anchor ($): M3 Faith_Matryoshka",',
     '《绝美之城》(2013, 保罗·索伦蒂诺 - 美学暗示) / 《兹玛蓝》(2019, 动画短片)',
     '\\"The Great Beauty\\" (2013, Paolo Sorrentino - aesthetic) / \\"Zima Blue\\" (2019, Short)'),
    ('coreEn: "Sensory peak encapsulated by harsh dogma. Violent rewrite of Empire identity. | Anchor ($): M4 Miniature_OCD",',
     '《我在伊朗长大》(2007, 玛雅·萨塔碧) / 《德黑兰禁忌》(2017, 阿里·苏赞德)',
     '\\"Persepolis\\" (2007, Marjane Satrapi) / \\"Tehran Taboo\\" (2017, Ali Soozandeh)')
]

process_file('/Users/lujiaqi/Desktop/【迷雾学派】爱欲视觉拓扑学 2-24版/data/engine_surface/SUR2/group_d.ts', reps_d)
