import os
import re

def process_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    
    for core_en_target, ref_cn, ref_en in replacements:
        replacement = f'{core_en_target}\n      reference: "{ref_cn}",\n      referenceEn: "{ref_en}",'
        content = content.replace(core_en_target, replacement)
        
    with open(filepath, 'w') as f:
        f.write(content)


reps_e = [
    ('coreEn: "Micro social war. Cruel class filtering in ball rites. | Anchor ($): M3 Lace_Noose",',
     '《傲慢与偏见》(2005, 乔·怀特) / 《理智与情感》(1995, 李安)',
     '\\"Pride & Prejudice\\" (2005, Joe Wright) / \\"Sense and Sensibility\\" (1995, Ang Lee)'),
    ('coreEn: "Violent order expansion. Absolute sacrifice when rail invades wild. | Anchor ($): M5 Wild_Derail",',
     '《西部往事》(1968, 赛尔乔·莱昂内) / 《不可饶恕》(1992, 克林特·伊斯特伍德)',
     '\\"Once Upon a Time in the West\\" (1968, Sergio Leone) / \\"Unforgiven\\" (1992, Clint Eastwood)'),
    ('coreEn: "Dual moral split. High-class hypocrisy vs slum total nakedness. | Anchor ($): M2 Soot_Mirror",',
     '《来自地狱》(2001, 艾尔伯斯·休斯) / 《雾都孤儿》(2005, 罗曼·波兰斯基)',
     '\\"From Hell\\" (2001, Albert Hughes) / \\"Oliver Twist\\" (2005, Roman Polanski)'),
    ('coreEn: "Cap inflates limitlessly. Money as sole algo rebuilding humanity. | Anchor ($): M1 Gold_Alienation",',
     '《血色将至》(2007, 保罗·托马斯·安德森) / 《镀金时代》(2022, 剧集)',
     '\\"There Will Be Blood\\" (2007, Paul Thomas Anderson) / \\"The Gilded Age\\" (2022, Series)'),
    ('coreEn: "Pains of paradigm. Old civ spirit collapse under full gen-gap strikes. | Anchor ($): M6 Shatter_Collapse",',
     '《末代皇帝》(1987, 贝纳尔多·贝托鲁奇) / 《投名状》(2007, 陈可辛)',
     '\\"The Last Emperor\\" (1987, Bernardo Bertolucci) / \\"The Warlords\\" (2007, Peter Chan)'),
    ('coreEn: "Phys stripping of identity. Severe pains of cutting soul memory to strengthen nation. | Anchor ($): M3 Restoration_Seppuku",',
     '《最后的武士》(2003, 爱德华·兹威克) / 《浪客剑心》(2012, 大友启史)',
     '\\"The Last Samurai\\" (2003, Edward Zwick) / \\"Rurouni Kenshin\\" (2012, Keishi Ohtomo)'),
    ('coreEn: "Calm before storm. Vaneer of boom joy hides underground rebel/void. | Anchor ($): M2 Fin_de_Siecle_Glow",',
     '《红磨坊》(2001, 巴兹·鲁赫曼) / 《午夜巴黎》(2011, 伍迪·艾伦)',
     '\\"Moulin Rouge!\\" (2001, Baz Luhrmann) / \\"Midnight in Paris\\" (2011, Woody Allen)'),
    ('coreEn: "Heart of darkness. Civilized man loses humanity to Id in alien wild. | Anchor ($): M4 Jungle_Mutate",',
     '《印度之行》(1984, 大卫·里恩) / 《殖民地之秋》(2015, 剧集 - 印度之夏)',
     '\\"A Passage to India\\" (1984, David Lean) / \\"Indian Summers\\" (2015-2016, Series)'),
    ('coreEn: "Violence of unequal swap. Free trade mask force-suturing worldviews. | Anchor ($): M6 Toxic_API_Port",',
     '《林则徐》(1959, 郑君里) / 《大班》(1986, 达里尔·杜克)',
     '\\"Lin Zexu\\" (1959, Zheng Junli) / \\"Tai-Pan\\" (1986, Daryl Duke)'),
    ('coreEn: "Flesh mechanization. Man downgraded to time units pushing bottom-line react. | Anchor ($): M1 Gear_Devour",',
     '《悲惨世界》(2012, 汤姆·霍珀) / 《北方与南方》(2004, 剧集)',
     '\\"Les Misérables\\" (2012, Tom Hooper) / \\"North & South\\" (2004, Series)'),
    ('coreEn: "Cost of justice. Releasing greater ind-war violence to abolish an evil. | Anchor ($): M5 Ethics_Artillery",',
     '《乱世佳人》(1939, 维克多·弗莱明) / 《林肯》(2012, 史蒂文·斯皮尔伯格)',
     '\\"Gone with the Wind\\" (1939, Victor Fleming) / \\"Lincoln\\" (2012, Steven Spielberg)'),
    ('coreEn: "Civ disconnect. Ultra-western nobles ruling desperate backward peasants. | Anchor ($): M3 Folded_Snowfield",',
     '《安娜·卡列尼娜》(2012, 乔·怀特) / 《日瓦戈医生》(1965, 大卫·里恩)',
     '\\"Anna Karenina\\" (2012, Joe Wright) / \\"Doctor Zhivago\\" (1965, David Lean)'),
    ('coreEn: "Trap of nostalgia. Elegant numbness to doom amidst refined culture. | Anchor ($): M2 Waltz_Sleep",',
     '《布达佩斯大饭店》(2014, 韦斯·安德森) / 《茜茜公主》(1955, 恩斯特·马里施卡)',
     '\\"The Grand Budapest Hotel\\" (2014, Wes Anderson) / \\"Sissi\\" (1955, Ernst Marischka)'),
    ('coreEn: "Hard collide of flesh & steel. Sad song of raw courage vs firearms. | Anchor ($): M1 Flesh_Shield",',
     '《祖鲁战争》(1964, 赛伊·恩菲尔德) / 《黎明之战》(1979, 道格拉斯·希科克斯)',
     '\\"Zulu\\" (1964, Cy Endfield) / \\"Zulu Dawn\\" (1979, Douglas Hickox)'),
    ('coreEn: "Superstition\'s mad bounce. Humiliation causes hallucinogenic deep self-harm. | Anchor ($): M4 God_Strike_Exploit",',
     '《北京55日》(1963, 尼古拉斯·雷) / 《黄飞鸿》(1991, 徐克)',
     '\\"55 Days at Peking\\" (1963, Nicholas Ray) / \\"Once Upon a Time in China\\" (1991, Tsui Hark)'),
    ('coreEn: "Mutant faith alienation. Savior utopia devolves into mad slaughters. | Anchor ($): M6 False_Heaven_Crash",',
     '《投名状》(2007, 陈可辛) / 《太平天国》(2000, 剧集)',
     '\\"The Warlords\\" (2007, Peter Chan) / \\"The Taiping Heavenly Kingdom\\" (2000, Series)'),
    ('coreEn: "Tech intervenes war. Rear\'s cruel drag on the first \'live-streamed\' conflict. | Anchor ($): M3 Live_Broadcast_Doom",',
     '《冲锋号》(1968, 托尼·理查德森) / 《提灯女神》(1985, 剧集)',
     '\\"The Charge of the Light Brigade\\" (1968, Tony Richardson) / \\"Florence Nightingale\\" (1985, TV Movie)'),
    ('coreEn: "Exotic toxin invasion. Colonist rot vs native awakening under repress. | Anchor ($): M4 Rubber_Narcotic",',
     '《情人》(1992, 让-雅克·阿诺) / 《印度支那》(1992, 瑞吉斯·瓦格涅)',
     '\\"The Lover\\" (1992, Jean-Jacques Annaud) / \\"Indochine\\" (1992, Régis Wargnier)'),
    ('coreEn: "Cruelty of truth. Discovering man is just random evolution causing psych crisis. | Anchor ($): M4 Species_Disenchant",',
     '《造物弄人》(2009, 乔恩·阿米尔) / 《怒海争锋》(2003, 彼得·威尔 - 包含科考线)',
     '\\"Creation\\" (2009, Jon Amiel) / \\"Master and Commander: The Far Side of the World\\" (2003, Peter Weir)'),
    ('coreEn: "2nd castration of nature. Eternal comm-labor after killing night. | Anchor ($): M5 Neon_Daylight",',
     '《电力之战》(2017, 阿方索·戈麦斯-雷洪) / 《致命魔术》(2006, 克里斯托弗·诺兰)',
     '\\"The Current War\\" (2017, Alfonso Gomez-Rejon) / \\"The Prestige\\" (2006, Christopher Nolan)')
]

reps_f = [
    ('coreEn: "Dawn of nihilism. Long waits in mud & senseless sacrifice. | Anchor ($): M1 Mud_Grinder",',
     '《1917》(2019, 萨姆·门德斯) / 《西线无战事》(2022, 爱德华·贝尔格)',
     '\\"1917\\" (2019, Sam Mendes) / \\"All Quiet on the Western Front\\" (2022, Edward Berger)'),
    ('coreEn: "Over-compensation. Sick hedonism from fleeing war trauma. | Anchor ($): M2 Bubble_Jazz",',
     '《了不起的盖茨比》(2013, 巴兹·鲁赫曼) / 《芝加哥》(2002, 罗伯·马歇尔)',
     '\\"The Great Gatsby\\" (2013, Baz Luhrmann) / \\"Chicago\\" (2002, Rob Marshall)'),
    ('coreEn: "Reality of lack. Dignity vs survival after sys crash. | Anchor ($): M1 Dust_Crash",',
     '《愤怒的葡萄》(1940, 约翰·福特) / 《铁拳男人》(2005, 朗·霍华德)',
     '\\"The Grapes of Wrath\\" (1940, John Ford) / \\"Cinderella Man\\" (2005, Ron Howard)'),
    ('coreEn: "Identity blur. Grey zone under crossed powers. | Anchor ($): M3 Island_Neon",',
     '《色，戒》(2007, 李安) / 《罗曼蒂克消亡史》(2016, 程耳)',
     '\\"Lust, Caution\\" (2007, Ang Lee) / \\"The Wasted Times\\" (2016, Cheng Er)'),
    ('coreEn: "Humanity\'s dark hour. Mechanized wipe after stripping identity. | Anchor ($): M1 Furnace_Ash",',
     '《辛德勒的名单》(1993, 史蒂文·斯皮尔伯格) / 《钢琴家》(2002, 罗曼·波兰斯基)',
     '\\"Schindler\'s List\\" (1993, Steven Spielberg) / \\"The Pianist\\" (2002, Roman Polanski)'),
    ('coreEn: "Rule by suspicion. Omnipotent spy net corroding personal sincerity. | Anchor ($): M4 Iron_Curtain_Static",',
     '《窃听风暴》(2006, 弗洛里安·亨克尔·冯·多纳斯马尔克) / 《间谍之桥》(2015, 史蒂文·斯皮尔伯格)',
     '\\"The Lives of Others\\" (2006, F. H. von Donnersmarck) / \\"Bridge of Spies\\" (2015, Steven Spielberg)'),
    ('coreEn: "Illusion clash. Frontline hell vs rear anti-establishment utopia. | Anchor ($): M6 Psychedelic_Napalm",',
     '《现代启示录》(1979, 弗朗西斯·福特·科波拉) / 《阿甘正传》(1994, 罗伯特·泽米吉斯)',
     '\\"Apocalypse Now\\" (1979, Francis Ford Coppola) / \\"Forrest Gump\\" (1994, Robert Zemeckis)'),
    ('coreEn: "Stiffened ideal. Structural violence & endless scale pressing micro. | Anchor ($): M4 Cast_Iron_Heart",',
     '《切尔诺贝利》(2019, 剧集) / 《列宁格勒》(2009, 亚历山大·布拉夫斯基)',
     '\\"Chernobyl\\" (2019, Series) / \\"Attack on Leningrad\\" (2009, Aleksandr Buravsky)'),
    ('coreEn: "Doomsday rave. Fast hazy peeling prompted by sensed end. | Anchor ($): M3 Fleeting_Neon",',
     '《堕落天使》(1995, 王家卫) / 《古惑仔》(1996, 刘伟强)',
     '\\"Fallen Angels\\" (1995, Wong Kar-wai) / \\"Young and Dangerous\\" (1996, Andrew Lau)'),
    ('coreEn: "Fake peak of desire. Drowning in consumer perfection before crash eve. | Anchor ($): M5 Plastic_Summer_Night",',
     '《全裸导演》(2019, 剧集) / 《东京爱情故事》(1991, 剧集)',
     '\\"The Naked Director\\" (2019, Series) / \\"Tokyo Love Story\\" (1991, Series)'),
    ('coreEn: "Sacrifice of pure ideal. Romantics\' bloody preview of Fascism vs Democracy. | Anchor ($): M1 Bloodie_Monument",',
     '《潘神的迷宫》(2006, 吉尔莫·德尔·托罗) / 《丧钟为谁而鸣》(1943, 山姆·伍德)',
     '\\"Pan\'s Labyrinth\\" (2006, Guillermo del Toro) / \\"For Whom the Bell Tolls\\" (1943, Sam Wood)'),
    ('coreEn: "Tech outsource of myth. Humans breach Earth logic via rockets. | Anchor ($): M6 Escape_Velocity",',
     '《登月第一人》(2018, 达米恩·查泽雷) / 《隐藏人物》(2016, 西奥多·梅尔菲)',
     '\\"First Man\\" (2018, Damien Chazelle) / \\"Hidden Figures\\" (2016, Theodore Melfi)'),
    ('coreEn: "River of time reverses. Modernity crushed under fundamental deity roar. | Anchor ($): M4 Inverted_Oracle",',
     '《逃离德黑兰》(2012, 本·阿弗莱克) / 《我在伊朗长大》(2007, 玛雅·萨塔碧)',
     '\\"Argo\\" (2012, Ben Affleck) / \\"Persepolis\\" (2007, Marjane Satrapi)'),
    ('coreEn: "Geological wound. Mirroring nation into forever-hostile virtual dual-zones. | Anchor ($): M3 Tundra_Mirror",',
     '《太极旗飘扬》(2004, 姜帝圭) / 《共同警备区》(2000, 朴赞郁)',
     '\\"Taegukgi\\" (2004, Kang Je-gyu) / \\"JSA: Joint Security Area\\" (2000, Park Chan-wook)'),
    ('coreEn: "Ethics of betrayal. Moral purgatory from symbolic terror expansion. | Anchor ($): M4 Red_Scare_Snitch",',
     '《特朗勃》(2015, 杰伊·罗奇) / 《晚安，好运》(2005, 乔治·克鲁尼)',
     '\\"Trumbo\\" (2015, Jay Roach) / \\"Good Night, and Good Luck.\\" (2005, George Clooney)'),
    ('coreEn: "Neighbor\'s Otherness. Modern harmony instantly torn by raw hate. | Anchor ($): M1 Shattered_Hunt",',
     '《无人地带》(2001, 丹尼斯·塔诺维奇) / 《萨拉热窝的罗密欧与朱丽叶》(1994, 纪录片)',
     '\\"No Man\'s Land\\" (2001, Danis Tanović) / \\"Romeo and Juliet in Sarajevo\\" (1994, Documentary)'),
    ('coreEn: "Money fetishized. Man reduced to hyper-aroused cap-bloat vessel. | Anchor ($): M5 Greed_Dopamine",',
     '《华尔街之狼》(2013, 马丁·斯科塞斯) / 《华尔街》(1987, 奥利佛·斯通)',
     '\\"The Wolf of Wall Street\\" (2013, Martin Scorsese) / \\"Wall Street\\" (1987, Oliver Stone)'),
    ('coreEn: "Language nuke-weaponized. Destructive experiment of absolute will forcing societal rebuild. | Anchor ($): M6 Word_Hunt",',
     '《霸王别姬》(1993, 陈凯歌) / 《芙蓉镇》(1986, 谢晋)',
     '\\"Farewell My Concubine\\" (1993, Chen Kaige) / \\"Hibiscus Town\\" (1986, Xie Jin)'),
    ('coreEn: "Doomsday game. Billions\' fate hangs on two leaders\' sweaty fingertips. | Anchor ($): M4 Nuke_Terror_Deadlock",',
     '《惊爆十三天》(2000, 罗杰·唐纳森) / 《奇爱博士》(1964, 斯坦利·库布里克)',
     '\\"Thirteen Days\\" (2000, Roger Donaldson) / \\"Dr. Strangelove\\" (1964, Stanley Kubrick)'),
    ('coreEn: "Peak oppressive taxonomy. Color encoded into unequal ontology. | Anchor ($): M3 B/W_Split",',
     '《第九区》(2009, 尼尔·布洛姆坎普 - 隐喻) / 《甘地传》(1982, 理查德·阿滕伯勒 - 南非段落)',
     '\\"District 9\\" (2009, Neill Blomkamp) / \\"Gandhi\\" (1982, Richard Attenborough)')
]

process_file('/Users/lujiaqi/Desktop/【迷雾学派】爱欲视觉拓扑学 2-24版/data/engine_surface/SUR2/group_e.ts', reps_e)
process_file('/Users/lujiaqi/Desktop/【迷雾学派】爱欲视觉拓扑学 2-24版/data/engine_surface/SUR2/group_f.ts', reps_f)
