import os
import re

def process_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    
    for core_en_target, ref_cn, ref_en in replacements:
        replacement = f'{core_en_target}\n      reference: "{ref_cn}",\n      referenceEn: "{ref_en}",'
        content = content.replace(core_en_target, replacement)
        
    with open(filepath, 'w') as f:
        f.write(content)


reps_g = [
    ('coreEn: "Self-compulsion from \'can do\'. No outer tyrant, each is own jailer. | Anchor ($): M1 Cell_Overload",',
     '《世界上最糟糕的人》(2021, 约阿希姆·提尔) / 《燃烧》(2018, 李沧东)',
     '\\"The Worst Person in the World\\" (2021, Joachim Trier) / \\"Burning\\" (2018, Lee Chang-dong)'),
    ('coreEn: "Man alienated to data packets. Extreme lonely powerless counted per sec. | Anchor ($): M2 Digital_Whip",',
     '《对不起，我们错过了你》(2019, 肯·洛奇) / 《无依之地》(2020, 赵婷)',
     '\\"Sorry We Missed You\\" (2019, Ken Loach) / \\"Nomadland\\" (2020, Chloé Zhao)'),
    ('coreEn: "Loss of Real. Life as act. Desire formatted by likes leaving void. | Anchor ($): M3 Aesthetic_Format",',
     '《霓虹恶魔》(2016, 尼古拉斯·温丁·雷弗恩) / 《英格丽向西行》(2017, 马特·斯派克)',
     '\\"The Neon Demon\\" (2016, Nicolas Winding Refn) / \\"Ingrid Goes West\\" (2017, Matt Spicer)'),
    ('coreEn: "Truth liquefied. When \'Real\' becomes editable code, man loses anchor. | Anchor ($): M5 Matrix_Glitch",',
     '《别向上看》(2021, 亚当·麦凯) / 《华盛顿邮报》(2017, 史蒂文·斯皮尔伯格)',
     '\\"Don\'t Look Up\\" (2021, Adam McKay) / \\"The Post\\" (2017, Steven Spielberg)'),
    ('coreEn: "Faultline sense. Trap of neither leaving nor staying. Coarse collage of trad & modern. | Anchor ($): M6 Neon_Dust",',
     '《任逍遥》(2002, 贾樟柯) / 《大象席地而坐》(2018, 胡波)',
     '\\"Unknown Pleasures\\" (2002, Jia Zhangke) / \\"An Elephant Sitting Still\\" (2018, Hu Bo)'),
    ('coreEn: "Visibility trap. Mass act from nowhere-to-hide, trading freedom for ease voluntarily. | Anchor ($): M4 Electronic_Lens",',
     '《楚门的世界》(1998, 彼得·威尔) / 《黑镜：急转直下》(2016, 剧集)',
     '\\"The Truman Show\\" (1998, Peter Weir) / \\"Black Mirror: Nosedive\\" (2016, Series)'),
    ('coreEn: "Rights stripped. Tension of \'remnants\' excreted in modern state cracks. | Anchor ($): M1 Mud_Exception",',
     '《何以为家》(2018, 娜丁·拉巴基) / 《人类之子》(2006, 阿方索·卡隆)',
     '\\"Capernaum\\" (2018, Nadine Labaki) / \\"Children of Men\\" (2006, Alfonso Cuarón)'),
    ('coreEn: "Peak fear. More owned = more fear of rob. Rich spiritually dying in self-jail. | Anchor ($): M3 Pure_O2_Safe",',
     '《寄生虫》(2019, 奉俊昊) / 《新秩序》(2020, 米歇尔·弗兰克)',
     '\\"Parasite\\" (2019, Bong Joon Ho) / \\"New Order\\" (2020, Michel Franco)'),
    ('coreEn: "God complex. Tech bros try modding genes to patch death, spawning unpredicted disasters. | Anchor ($): M5 Hubris_Singularity",',
     '《机械姬》(2014, 亚历克斯·加兰) / 《硅谷》(2014-2019, 剧集)',
     '\\"Ex Machina\\" (2014, Alex Garland) / \\"Silicon Valley\\" (2014-2019, Series)'),
    ('coreEn: "Will loss. Joyous voluntary capture, subject shatters in frag info. | Anchor ($): M2 Infinite_Scroll",',
     '《社交网络》(2010, 大卫·芬奇) / 《智能陷阱》(2020, 纪录片)',
     '\\"The Social Network\\" (2010, David Fincher) / \\"The Social Dilemma\\" (2020, Documentary)'),
    ('coreEn: "Passive resist. Refusing Other\'s compete track, paying with one-way social death ticket. | Anchor ($): M1 Island_Mute",',
     '《被嫌弃的松子的一生》(2006, 中岛哲也) / 《百元之恋》(2014, 武正晴)',
     '\\"Memories of Matsuko\\" (2006, Tetsuya Nakashima) / \\"100 Yen Love\\" (2014, Masaharu Take)'),
    ('coreEn: "Joy of mechanic repeat. Subject dissolves conscious shape in BPM hammering. | Anchor ($): M2 Strobe_Disillusion",',
     '《柏林召唤》(2008, 汉内斯·斯托尔) / 《高潮》(2018, 加斯帕·诺)',
     '\\"Berlin Calling\\" (2008, Hannes Stöhr) / \\"Climax\\" (2018, Gaspar Noé)'),
    ('coreEn: "Fragile decency. Used massive consumerist moat to hide weak anti-risk capacity. | Anchor ($): M3 Class_Kevlar",',
     '《爱情神话》(2021, 邵艺辉) / 《小欢喜》(2019, 剧集)',
     '\\"B Myth of Love\\" (2021, Shao Yihui) / \\"A Little Reunion\\" (2019, Series)'),
    ('coreEn: "Cyber outsource of id. Selling local persona for cheap hourly wage to act perfect CS symbol. | Anchor ($): M4 Vocal_Ghost",',
     '《贫民窟的百万富翁》(2008, 丹尼·博伊尔) / 《白老虎》(2021, 拉敏·巴赫拉尼)',
     '\\"Slumdog Millionaire\\" (2008, Danny Boyle) / \\"The White Tiger\\" (2021, Ramin Bahrani)'),
    ('coreEn: "Taxidermy of logic. All history/culture hollowed, downgraded to check-in backdrop. | Anchor ($): M5 Plastic_Specimen",',
     '《午夜巴塞罗那》(2008, 伍迪·艾伦) / 《爱在黎明破晓前》(1995, 理查德·林克莱特)',
     '\\"Vicky Cristina Barcelona\\" (2008, Woody Allen) / \\"Before Sunrise\\" (1995, Richard Linklater)'),
    ('coreEn: "Uncontrollable sys-accel. Man reduced to carbon plug-in for AI sorting arm. | Anchor ($): M2 Sort_Countdown",',
     '《无依之地》(2020, 赵婷) / 《摩登时代》(1936, 查理·卓别林)',
     '\\"Nomadland\\" (2020, Chloé Zhao) / \\"Modern Times\\" (1936, Charlie Chaplin)'),
    ('coreEn: "Peak space split. Radiant digital utopia crit-strikes bleak flesh Real. | Anchor ($): M1 Leaky_VR",',
     '《头号玩家》(2018, 史蒂文·斯皮尔伯格) / 《未来学大会》(2013, 阿里·福尔曼)',
     '\\"Ready Player One\\" (2018, Steven Spielberg) / \\"The Congress\\" (2013, Ari Folman)'),
    ('coreEn: "Norming exception state. Biopolitic safety wipes all warmth of human connection. | Anchor ($): M4 Green_Code_Pass",',
     '《传染病》(2011, 史蒂文·索德伯格) / 《末日孤舰》(2014-2018, 剧集)',
     '\\"Contagion\\" (2011, Steven Soderbergh) / \\"The Last Ship\\" (2014-2018, Series)'),
    ('coreEn: "Alt religion. In secular era post-God, warm-climate acts as new original-sin eschatology. | Anchor ($): M6 Carbon_Sin",',
     '《第一归正会》(2017, 保罗·施拉德) / 《夜色行动》(2013, 凯莉·雷查德)',
     '\\"First Reformed\\" (2017, Paul Schrader) / \\"Night Moves\\" (2013, Kelly Reichardt)'),
    ('coreEn: "Peak objectify. Scalpel-slicing oneself into standardized goods fitting algo preferences. | Anchor ($): M3 Silicone_Mask",',
     '《钛》(2021, 朱利亚·迪库诺) / 《整容液》(2020, 动漫)',
     '\\"Titane\\" (2021, Julia Ducournau) / \\"Beauty Water\\" (2020, Animation)')
]

reps_h = [
    ('coreEn: "Uncanny valley. Proximity to reality makes rational tiny-twists more chilling. | Anchor ($): M4 Rating_Terminal",',
     '《黑镜：急转直下》(2016, 剧集) / 《她》(2013, 斯派克·琼斯)',
     '\\"Black Mirror: Nosedive\\" (2016, Series) / \\"Her\\" (2013, Spike Jonze)'),
    ('coreEn: "Devalue of flesh. Souls coded, wealth gap evos into species gap. Base-layer rebel. | Anchor ($): M1 Neon_Cyber_Eye",',
     '《银翼杀手2049》(2017, 丹尼斯·维伦纽瓦) / 《攻壳机动队》(1995, 押井守)',
     '\\"Blade Runner 2049\\" (2017, Denis Villeneuve) / \\"Ghost in the Shell\\" (1995, Mamoru Oshii)'),
    ('coreEn: "Blasphemy of Nature. Life loses sanctity, becomes cheap dissectible material. | Anchor ($): M3 Pulsing_Wall",',
     '《异形》(1979, 雷德利·斯科特) / 《变蝇人》(1986, 大卫·柯南伯格)',
     '\\"Alien\\" (1979, Ridley Scott) / \\"The Fly\\" (1986, David Cronenberg)'),
    ('coreEn: "Moral regression. Under extreme survive-pressure, human rebuilds violent \'civ\'. | Anchor ($): M2 Rad_Cola",',
     '《疯狂的麦克斯4：狂暴之路》(2015, 乔治·米勒) / 《艾利之书》(2010, 休斯兄弟)',
     '\\"Mad Max: Fury Road\\" (2015, George Miller) / \\"The Book of Eli\\" (2010, Hughes Brothers)'),
    ('coreEn: "Nihilism of scale. Before light-year distances, solo struggles seem sublime yet trivial. | Anchor ($): M6 Star_Killer_Fleet",',
     '《沙丘》(2021, 丹尼斯·维伦纽瓦) / 《星球大战：帝国反击战》(1980, 厄文·克什纳)',
     '\\"Dune\\" (2021, Denis Villeneuve) / \\"Star Wars: Episode V - The Empire Strikes Back\\" (1980, Irvin Kershner)'),
    ('coreEn: "Illusion of being. W/o phys pain & death threat, does life hold meaning? Peak fear of power-out. | Anchor ($): M5 Blue_Pod",',
     '《黑客帝国》(1999, 沃卓斯基姐妹) / 《上载新生》(2020, 剧集)',
     '\\"The Matrix\\" (1999, The Wachowskis) / \\"Upload\\" (2020-2023, Series)'),
    ('coreEn: "Creator\'s fear. Creations demand sovereignty, breaking logic loop for un-preset emotion/violence. | Anchor ($): M1 Blue_Blood",',
     '《西部世界》(2016-2022, 剧集) / 《人工智能》(2001, 史蒂文·斯皮尔伯格)',
     '\\"Westworld\\" (2016-2022, Series) / \\"A.I. Artificial Intelligence\\" (2001, Steven Spielberg)'),
    ('coreEn: "Phys bounds of survive. O2 & H2O as ruling tools. Base-tier mutual aid & betray under high risk. | Anchor ($): M2 Leaking_Airlock",',
     '《苍穹浩瀚》(2015-2022, 剧集) / 《月球》(2009, 邓肯·琼斯)',
     '\\"The Expanse\\" (2015-2022, Series) / \\"Moon\\" (2009, Duncan Jones)'),
    ('coreEn: "Invisible foe. Humans can\'t fight exp-growing micro-force. Slow civ dissolve. | Anchor ($): M3 Grey_Dust",',
     '《地球停转之日》(2008, 斯科特·德瑞克森) / 《湮灭》(2018, 亚历克斯·加兰)',
     '\\"The Day the Earth Stood Still\\" (2008, Scott Derrickson) / \\"Annihilation\\" (2018, Alex Garland)'),
    ('coreEn: "Absolute Otherness. Aliens care not for us, like we care not for ants. Cog-downgrade strike. | Anchor ($): M6 Floating_Heptapod",',
     '《降临》(2016, 丹尼斯·维伦纽瓦) / 《三体》(2023, 剧集)',
     '\\"Arrival\\" (2016, Denis Villeneuve) / \\"3 Body Problem\\" (2024, Series)'),
    ('coreEn: "Reconciliation w/ nature. Aesthetic def-mech against doomsday anxiety. | Anchor ($): M1 Solar_Green_Wall",',
     '《风之谷》(1984, 宫崎骏) / 《阿凡达》(2009, 詹姆斯·卡梅隆)',
     '\\"Nausicaä of the Valley of the Wind\\" (1984, Hayao Miyazaki) / \\"Avatar\\" (2009, James Cameron)'),
    ('coreEn: "Exile epic. Old world becomes sea legend. Human struggles on floating fragile islands. | Anchor ($): M4 Rusty_Pontoon",',
     '《未来水世界》(1995, 凯文·雷诺兹) / 《雪国列车》(2013, 奉俊昊)',
     '\\"Waterworld\\" (1995, Kevin Reynolds) / \\"Snowpiercer\\" (2013, Bong Joon Ho)'),
    ('coreEn: "Cage of artificial nature. When cosmos is locked OUT by human metal shells, inf safety turns to inf claustrophobia. | Anchor ($): M3 Star_Collector_Ring",',
     '《星际穿越》(2014, 克里斯托弗·诺兰) / 《流浪地球》(2019, 郭帆)',
     '\\"Interstellar\\" (2014, Christopher Nolan) / \\"The Wandering Earth\\" (2019, Frant Gwo)'),
    ('coreEn: "Exile in time. When all u loved are ashes, how to prove ur being in a future foreign land? | Anchor ($): M5 Cryo_Frost_Pod",',
     '《太空旅客》(2016, 莫滕·泰杜姆) / 《星际牛仔》(1998, 动漫剧集)',
     '\\"Passengers\\" (2016, Morten Tyldum) / \\"Cowboy Bebop\\" (1998, Anime Series)'),
    ('coreEn: "Dissolve of truth. Even most painful truth is more dignified than sweetest lie. Rage vs code-deceit. | Anchor ($): M6 Red_Pill_Code",',
     '《楚门的世界》(1998, 彼得·威尔) / 《异次元骇客》(1999, 约瑟夫·鲁斯纳克)',
     '\\"The Truman Show\\" (1998, Peter Weir) / \\"The Thirteenth Floor\\" (1999, Josef Rusnak)'),
    ('coreEn: "Shattered uniqueness. If inf \'Me\'s exist, do choices of current \'Me\' matter? | Anchor ($): M4 Ghosted_Photo",',
     '《瞬息全宇宙》(2022, 关家永/丹尼尔·施因内特) / 《前目的地》(2014, 斯派瑞兄弟)',
     '\\"Everything Everywhere All at Once\\" (2022, Daniels) / \\"Predestination\\" (2014, The Spierig Brothers)'),
    ('coreEn: "End of privacy & lonely. Eradicating lies while utterly erasing the shell called \'I\'. | Anchor ($): M1 Neuro_Node_Chip",',
     '《超体》(2014, 吕克·贝松) / 《新世纪福音战士剧场版：Air/真心为你》(1997, 庵野秀明)',
     '\\"Lucy\\" (2014, Luc Besson) / \\"The End of Evangelion\\" (1997, Hideaki Anno)'),
    ('coreEn: "Abandoned creations. When machines lose use-value, how do they sim human society to find solace? | Anchor ($): M2 Leaking_Tin",',
     '《第九区》(2009, 尼尔·布洛姆坎普) / 《阿丽塔：战斗天使》(2019, 罗伯特·罗德里格兹)',
     '\\"District 9\\" (2009, Neill Blomkamp) / \\"Alita: Battle Angel\\" (2019, Robert Rodriguez)'),
    ('coreEn: "Tech-rebirth of Bloodline theory. When sweat means nothing before perfect gen-params, rebel is just self-destruct. | Anchor ($): M5 Perfect_Helix",',
     '《千钧一发》(1997, 安德鲁·尼科尔) / 《美丽新世界》(2020, 剧集)',
     '\\"Gattaca\\" (1997, Andrew Niccol) / \\"Brave New World\\" (2020, Series)'),
    ('coreEn: "Peak weariness of existence. Only via abs-crush that even light can\'t flee, can human triviality be wiped. | Anchor ($): M6 Event_Horizon_Orb",',
     '《黑洞表面》(1997, 保罗·安德森) / 《迷失太空》(1998, 斯蒂芬·霍普金斯)',
     '\\"Event Horizon\\" (1997, Paul W. S. Anderson) / \\"Lost in Space\\" (1998, Stephen Hopkins)')
]

process_file('/Users/lujiaqi/Desktop/【迷雾学派】爱欲视觉拓扑学 2-24版/data/engine_surface/SUR2/group_g.ts', reps_g)
process_file('/Users/lujiaqi/Desktop/【迷雾学派】爱欲视觉拓扑学 2-24版/data/engine_surface/SUR2/group_h.ts', reps_h)
