#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           🚀 启动 Visionary 应用 - 3个终端                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ 环境变量已配置完成！"
echo ""
echo "现在按照以下步骤启动应用："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 终端1 - 启动后端服务器"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "复制此命令到终端1："
echo ""
echo "  cd backend && npm install && npm run dev"
echo ""
echo "预期输出："
echo "  Server running on port 3001"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 终端2 - 启动前端应用"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "复制此命令到终端2（确保在项目根目录）："
echo ""
echo "  npm install && npm run dev"
echo ""
echo "预期输出："
echo "  Local:   http://localhost:5173/"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 终端3 - 验证 API 工作"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "复制此命令到终端3（等后端和前端都启动完成后运行）："
echo ""
echo "  curl http://localhost:3001/health"
echo ""
echo "预期输出："
echo "  {\"status\":\"ok\",\"timestamp\":\"...\"}"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ 完成后"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "打开浏览器访问："
echo ""
echo "  http://localhost:5173"
echo ""
echo "应该看到应用正常加载！"
echo ""
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                 💡 完整命令快速参考                            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "后端："
echo "  cd backend && npm install && npm run dev"
echo ""
echo "前端："
echo "  npm install && npm run dev"
echo ""
echo "验证："
echo "  curl http://localhost:3001/health"
echo "  curl http://localhost:3001/api/data/categories"
echo ""
echo "🎉 准备就绪！现在启动吧！"
echo ""
