import { LibraryItemDef } from '../../../types';

export const SUBJECTS_GROUP_A: LibraryItemDef[] = [
    // ============================================================
    // GROUP A. 被吞没的主体 (The Absorbed) - 16 Items
    // 缺失方向：向上 → 系统/权力。主体被功能、角色或体制所覆盖。
    // ============================================================
    {
        id: "subj_cog",
        name: "齿轮", nameEn: "The Gear",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "庞大运转体系中按部就班的功能部件。",
        defEn: "A component operating in lockstep within a vast, churning system.",
        flaw: "习得性无助", flawEn: "Learned Helplessness",
        core: "重复可以是安定的节拍，也可以是磨损的枷锁。关键张力：如果齿轮停转——迎来的是自由，还是坠落？ | 缺失 ($): 主体性",
        coreEn: "Repetition can be a comforting rhythm or a grinding shackle. Key tension: if the gear stops turning — is it freedom, or freefall? | Lacks ($): Subjectivity",
        reference: "《摩登时代》查理（被流水线吞噬的工人）；《审判》K（在庞大官僚机器中被消耗的个体）；《黑客帝国》母体外的培养皿沉睡者。",
        referenceEn: "Charlie in Modern Times (a worker swallowed by the assembly line); K in The Trial (an individual consumed within a massive bureaucracy); sleepers in the pods outside The Matrix."
    },
    {
        id: "subj_cleaner",
        name: "清道夫", nameEn: "The Scavenger",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "专门处理体系运转中产生的残余与不可言说之事的人。",
        defEn: "One who handles the residue and unspeakable byproducts generated by a system's operations.",
        flaw: "道德污染", flawEn: "Moral Contamination",
        core: "知晓帷幕背后的真相，却注定缄默。沉默可以是一种力量，也可以是缓慢的腐蚀。关键张力：当沉默本身成为共谋，开口是救赎还是毁灭？ | 缺失 ($): 洁净",
        coreEn: "Knowing the truth behind the curtain yet sworn to silence. Silence can be a form of power or a slow corrosion. Key tension: when silence itself becomes complicity, is speaking up salvation or destruction? | Lacks ($): Innocence",
        reference: "《教父》卢卡·布拉西（替家族包揽最肮脏暴力的清道夫）；《甄嬛传》苏培盛（负责处理后宫腌臜的执行者）；《银翼杀手》中专门清理复制人的同类退役警察。",
        referenceEn: "Luca Brasi in The Godfather (a scavenger handling the family's dirtiest violence); Su Peisheng in Empresses in the Palace (executing the harem's sordid affairs); the retired cop hunting his own kind in Blade Runner."
    },
    {
        id: "subj_battery",
        name: "薪柴", nameEn: "The Kindling",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "被置于持续供能的位置——为他人、系统或信念输出自身的体力与心血。",
        defEn: "Placed in the position of a perpetual energy source — pouring out physical or emotional labor for others, systems, or beliefs.",
        flaw: "极度枯竭", flawEn: "Burnout",
        core: "持续给予可以是崇高的使命感，也可以是无声的枯竭。关键张力：供给者何时意识到燃料是自己的血肉？ | 缺失 ($): 生命力",
        coreEn: "Ceaseless giving can be a sublime sense of mission or a silent withering. Key tension: when does the provider realize the fuel is their own flesh? | Lacks ($): Vitality",
        reference: "《包身工》中的纺织女工（被榨干生命力的血肉电池）；《活着》中的福贵；《疯狂的麦克斯：狂暴之路》中被吊起抽血的'血袋'。",
        referenceEn: "Textile workers in Xia Yan's Indentured Servants (flesh batteries drained of vitality); Fugui in To Live; the 'blood bags' hung up for extraction in Mad Max: Fury Road."
    },
    {
        id: "subj_prosthesis",
        name: "执行者", nameEn: "The Enforcer",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "充当更强大意志的执行器——双手遵从的是他人的指令。",
        defEn: "Serving as the executor of a stronger will — the hands obey commands that are not one's own.",
        flaw: "缺乏自主", flawEn: "Lack of Agency",
        core: "在代行命令中获得确定性，但那份确定感不属于自己。关键张力：当命令与良知冲突，执行器有资格犹豫吗？ | 缺失 ($): 意志",
        coreEn: "Executing orders provides certainty, but that certainty is borrowed. Key tension: when orders clash with conscience, does the instrument have the right to hesitate? | Lacks ($): Will",
        reference: "《水浒传》陆谦（放弃个人意志，沦为权贵爪牙）；明代东厂武役（只作为皇权的物理痛觉制造器）；《指环王》中被索伦意志完全取代的戒灵。",
        referenceEn: "Lu Qian in Water Margin (surrendering personal will to become a henchman); Ming Dynasty's Eastern Depot agents (functioning purely as the emperor's tool of pain); the Nazgûl in The Lord of the Rings, wholly subsumed by Sauron's will."
    },
    {
        id: "subj_ornament",
        name: "标本 / 陈列品", nameEn: "The Exhibit",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "存在的价值建立在被观赏、被展示之上。",
        defEn: "Existing primarily to be gazed upon and displayed by an owner or audience.",
        flaw: "自我客体化", flawEn: "Self-Objectification",
        core: "被凝视可以是光芒万丈的舞台，也可以是密不透风的玻璃罩。关键张力：当观众散去，展品是否还有理由存在？ | 缺失 ($): 内核",
        coreEn: "Being gazed upon can be a radiant stage or a suffocating glass case. Key tension: when the audience leaves, does the exhibit still have a reason to exist? | Lacks ($): Depth",
        reference: "《了不起的盖茨比》黛西（被当作阶级跨越的完美战利品）；中国古代待价而沽的'扬州瘦马'；《银翼杀手2049》中的虚拟全息女友乔伊（被定制的凝视客体）。",
        referenceEn: "Daisy in The Great Gatsby (the perfect trophy of class mobility); ancient Chinese 'Yangzhou skinny horses' sold to the highest bidder; Joi, the customizable holographic girlfriend in Blade Runner 2049."
    },
    {
        id: "subj_number",
        name: "烙印", nameEn: "The Brand",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "名字被档案编号、法律身份或集体标签所替代的人。",
        defEn: "A person whose name has been replaced by file numbers, legal identities, or collective labels.",
        flaw: "去人格化", flawEn: "Depersonalization",
        core: "在宏大的账簿里，个体被缩减为一行代码。但即便是代码，也可能藏着不被系统识别的暗号。关键张力：当有人念出了你真正的名字，你敢应答吗？ | 缺失 ($): 姓名",
        coreEn: "In the grand ledger, a person is reduced to a line of code. Yet even within a code, a secret cipher the system cannot read may be hidden. Key tension: when someone speaks your true name, do you dare answer? | Lacks ($): Name",
        reference: "《悲惨世界》冉·阿让（只剩下代号24601的苦役犯）；奥斯维辛集中营被烙上数字的犹太人；反乌托邦小说《我们》中只有编号没有名字的统一国公民。",
        referenceEn: "Jean Valjean in Les Misérables (a convict reduced to 24601); Jews branded with numbers in Auschwitz; the numbered citizens in the dystopian novel We."
    },
    {
        id: "subj_spare_part",
        name: "替补", nameEn: "The Double",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "为了随时填补某人的空缺而存在的影子——候补者、备胎、替身。",
        defEn: "A shadow existing to fill someone's vacancy at any moment — the understudy, the spare, the stand-in.",
        flaw: "多余感", flawEn: "Redundancy",
        core: "活在等待被需要的悬停中。等待可以是忠诚的修行，也可以是存在的悬空。关键张力：正主倒下的那天，是解放还是更深的空洞？ | 缺失 ($): 独特性",
        coreEn: "Living in a suspended state of waiting to be needed. Waiting can be a loyal discipline or an existential limbo. Key tension: the day the original falls — is it liberation, or an even deeper void? | Lacks ($): Uniqueness",
        reference: "张艺谋《影》中的境州（从小豢养，只为替主公挡刀）；《红楼梦》中随时准备顶替主子赴死的丫鬟；石黑一雄《别让我走》中只为给本体提供器官而活的克隆人。",
        referenceEn: "Jingzhou in Zhang Yimou's Shadow (raised since childhood solely to take a blade for his lord); maids in Dream of the Red Chamber ready to die for their mistresses; the clones living only for organ donation in Never Let Me Go."
    },
    {
        id: "subj_algorithm",
        name: "发条人 / 苦役", nameEn: "The Clockwork",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "行为节律被严苛的外部规则或精确的时间表完全接管的人。",
        defEn: "A person whose behavioral rhythms are entirely commandeered by stringent external rules or precise timetables.",
        flaw: "节律焦虑", flawEn: "Time Anxiety",
        core: "精密的节拍可以是效率的美学，也可以是自由意志的溺毙。关键张力：如果时钟突然失灵，发条人是终于喘息，还是彻底瓦解？ | 缺失 ($): 停歇",
        coreEn: "Precise rhythm can be an aesthetic of efficiency or the drowning of free will. Key tension: if the clock suddenly breaks, does the clockwork finally breathe — or completely collapse? | Lacks ($): Rest",
        reference: "《骆驼祥子》祥子（在城市暴雨中至死奔跑的肉身苦力）；维多利亚时代的计件童工；赛博朋克中被隐形算法和倒计时疯狂剥削的网约车与外卖员。",
        referenceEn: "Xiangzi in Rickshaw Boy (running to his death in the city rain); Victorian-era piece-rate child labor; gig workers in cyberpunk worlds ruthlessly exploited by invisible algorithms and countdowns."
    },
    {
        id: "subj_filter",
        name: "食罪者", nameEn: "The Sin-Eater",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "替他人承接负面情绪、秘密或罪责的容器。",
        defEn: "A vessel that absorbs the negative emotions, secrets, or guilt of others.",
        flaw: "深渊污染", flawEn: "Trauma Exposure",
        core: "替人吞下苦涩可以是一种温柔的牺牲，也可以是精神的慢性中毒。关键张力：当容器满溢，是倾倒还是爆裂？ | 缺失 ($): 精神屏障",
        coreEn: "Swallowing bitterness for others can be a tender sacrifice or a slow spiritual poisoning. Key tension: when the vessel overflows, does it pour out — or shatter? | Lacks ($): Sanity",
        reference: "中世纪民间'食罪者'（替死去的贵族吃下象征罪孽的面包）；封建宫廷里的试毒太监；每天被迫观看并过滤全网血腥色情视频的现代内容审核员。",
        referenceEn: "Medieval 'sin-eaters' (consuming bread representing a dead noble's sins); poison-tasting eunuchs in feudal courts; modern content moderators forced to watch and filter gory/explicit videos daily."
    },
    {
        id: "subj_moderator",
        name: "守门人", nameEn: "The Gatekeeper",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "处于卑微的位置，却攥着一点发放通行或拒绝的微小权力。",
        defEn: "Positioned at the bottom, yet clutching the tiny power to grant passage or deny it.",
        flaw: "权力的幻觉", flawEn: "Petty Power",
        core: "微权可以是微弱的尊严火种，也可以是自我的毒瘾。关键张力：当同样卑微的人跪在面前，我会想起自己曾经也跪过吗？ | 缺失 ($): 尊严底座",
        coreEn: "Petty power can be a faint ember of dignity or a toxic addiction to self. Key tension: when someone equally wretched kneels before me, will I remember that I, too, once knelt? | Lacks ($): Dignity",
        reference: "卡夫卡《法的门前》里的守门人（手握进入窄门的一丝微小权力）；古代衙门向落难者索要打点费的牢头；反乌托邦游戏《请出示证件》中决定他人生死的边境审查员。",
        referenceEn: "The gatekeeper in Kafka's Before the Law; ancient jailers extracting bribes from the desperate; the border inspector dealing life or death in Papers, Please."
    },
    {
        id: "subj_dummy",
        name: "挡箭牌 / 缓冲者", nameEn: "The Shield",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "被安放在冲突交汇处，替上方的人承受冲击的缓冲角色。",
        defEn: "Placed at the nexus of conflict, a buffer designated to absorb impacts aimed at those above.",
        flaw: "创伤麻木", flawEn: "Numbness",
        core: "反复承受撞击可以磨出铁骨，也可以磨灭痛觉。关键张力：当缓冲者不再感到疼痛，他是变强了还是已经死了？ | 缺失 ($): 痛觉的权利",
        coreEn: "Enduring blows repeatedly can forge iron bones or erode the ability to feel. Key tension: when the buffer no longer feels pain, have they grown stronger — or already died inside? | Lacks ($): Feeling",
        reference: "欧洲中世纪宫廷里的'挨鞭童'（专门替犯错的王子受罚的平民玩伴）；职场体制中专替高层平息群氓怒火的'黑锅侠'；《疯狂的麦克斯》里被绑在车头当人肉护盾的战争男孩。",
        referenceEn: "'Whipping boys' of medieval courts (commoners taking punishment for princes); corporate fall-guys hired to absorb mob anger for executives; War Boys strapped to bumpers as meat shields in Mad Max."
    },
    {
        id: "subj_npc",
        name: "游魂 / 背景底色", nameEn: "The Extra",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "深感自己只配充当他人故事的虚化背景。",
        defEn: "Deeply feeling destined to be nothing more than blurred background in the stories of others.",
        flaw: "极度平庸", flawEn: "Fear of Mediocrity",
        core: "在命运织就的花毯上，觉得自己不配拥有一根彩色丝线。但有时最安全的位置恰恰是无人注目之处。关键张力：被看见，到底是祝福还是诅咒？ | 缺失 ($): 天命与高光",
        coreEn: "On destiny's woven tapestry, feeling unworthy of a single colored thread. Yet sometimes the safest place is precisely where no one is looking. Key tension: is being seen a blessing or a curse? | Lacks ($): Protagonism",
        reference: "大时代史诗里随便死于兵荒马乱的流民；《红楼梦》卷首一闪而过的乡野村妇；游戏电影《失控玩家》中日复一日执行同一句对白、注定无缘主线任务的NPC。",
        referenceEn: "Refugees perishing randomly in epic eras; the fleeting countrywoman opening Dream of the Red Chamber; the NPC doomed to recite the same line forever without a main quest in Free Guy."
    },
    {
        id: "subj_uniform",
        name: "盔甲 / 制服", nameEn: "The Uniform",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "身份被职业外壳、制服或社会角色完全覆盖的人。",
        defEn: "A person whose identity is entirely covered by a professional shell, uniform, or social role.",
        flaw: "面具吞噬", flawEn: "Role Fixation",
        core: "壳可以是保护，也可以是牢笼。关键张力：脱下制服后的那张脸，自己还认得吗？ | 缺失 ($): 本源血肉",
        coreEn: "A shell can be protection or a cage. Key tension: the face beneath the uniform — do you still recognize it? | Lacks ($): Individuality",
        reference: "《西线无战事》中的普通士兵（被强行缝入军装，失去作为人的喘息）；被严苛封建'宗法'彻底吞噬了人性的卫道士；《星球大战》中连面容和情感都被白色盔甲标准化的暴风兵。",
        referenceEn: "The regular soldiers in All Quiet on the Western Front (stitched into uniforms without a breath for humanity); moral guardians totally devoured by strict feudal law; Stormtroopers in Star Wars whose very faces and emotions are standardized by white armor."
    },
    {
        id: "subj_hand",
        name: "百巧之手", nameEn: "The Hands",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "身体的某个部位或某项天赋被过度神化，凌驾于完整生命之上。",
        defEn: "A single body part or talent is excessively deified, overriding the value of the whole life.",
        flaw: "器官割裂", flawEn: "Synecdoche",
        core: "被世人追捧的那双手，可以是骄傲的王冠，也可以是锁住余生的枷。关键张力：如果天赋消失，剩下的那个人还值得被爱吗？ | 缺失 ($): 存在的完整性",
        coreEn: "The hands the world celebrates can be a proud crown or a lock on the rest of one's life. Key tension: if the talent vanishes, is the person who remains still worth loving? | Lacks ($): Wholeness",
        reference: "《霸王别姬》程蝶衣（嗓子身段被剥削到极致倒逼自己割裂原生性别）；古代替皇陵雕刻机关事毕后被剁去双手的巧匠；废土世界中被截肢并换上夺命机械臂的血肉改造工具。",
        referenceEn: "Cheng Dieyi in Farewell My Concubine (his voice and posture exploited to the point of fracturing his native gender); ancient tomb artisans getting their hands chopped off to secure secrets; post-apocalyptic mercenaries amputated to wield killer metallic arms."
    },
    {
        id: "subj_ear",
        name: "倾听的树洞", nameEn: "The Ear",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "不可抗拒地成为他人倾诉秘密、罪责或痛苦的容器。",
        defEn: "Irresistibly becoming the vessel into which others pour their secrets, guilt, or suffering.",
        flaw: "精神淤积", flawEn: "Burden of Secrets",
        core: "被信任是一种特权，但当他人的重量堆满颅骨，却找不到向外倾倒的出口。关键张力：替全世界消化了苦涩，谁来替我消化？ | 缺失 ($): 豁免与排解",
        coreEn: "Being trusted is a privilege, yet when others' weight fills the skull, no outlet can be found to pour it away. Key tension: having digested the world's bitterness, who will digest mine? | Lacks ($): Expression",
        reference: "《玫瑰的名字》中听取了太多阴暗诡计而濒临疯癫的修士；封建深宫中被强行毒哑专门侍奉起居的聋哑奴仆；反乌托邦社会里被无数狂躁公民当成赛博发泄孔的情绪处理中心接线员。",
        referenceEn: "The monk driven mad by dark secrets in The Name of the Rose; deaf-mute servants poisoned in feudal palaces purely to serve without telling tales; the dystopia's mood operators treated as cyber-vents by manic citizens."
    },
    {
        id: "subj_foot",
        name: "无休之足", nameEn: "The Wandering Foot",
        group: "A. 被吞没的主体", groupEn: "The Absorbed",
        def: "命运注定无法长久停留——永远在路上的驿卒、逃亡者或漫游者。",
        defEn: "Fated never to stay — the eternal courier, fugitive, or wanderer always on the road.",
        flaw: "剥夺停歇", flawEn: "Restlessness",
        core: "永不停歇可以是自由的极致，也可以是归属的永恒缺席。关键张力：当所有故乡都关上了门，脚步本身能成为家吗？ | 缺失 ($): 归宿定点",
        coreEn: "Never stopping can be the pinnacle of freedom or the eternal absence of belonging. Key tension: when every homeland has shut its door, can the journey itself become home? | Lacks ($): Destination",
        reference: "《悲惨世界》中只要停顿就会被残酷律法捕捉的冉·阿让；大漠里跑死在黄沙驿道上的八百里加急传令兵；《雪国列车》中必须要不断绕行地球否则就会冻死的末日遗民。",
        referenceEn: "Jean Valjean in Les Misérables, hunted by cruel law the moment he pauses; emergency couriers dropping dead on desert post roads; the survivors of Snowpiercer who must orbit the globe endlessly or freeze."
    }
];

